### ISSUE TITLE
3.3 plugins are the "exceptional" case

### ISSUE THREAD

**Issue by FichteFoll** [kapitanluffy/sublime-plugin-logger#1]
When loading plugins, ST4 explicitly mentions the Python version only for Python 3.3 plugins and not for 3.8 because those are the new default.

Also, you can detect/build what Python version your code is running in via `'.'.join(str(v) for v in sys.version_info[:2])`.

**Comment by kapitanluffy** [comment]
Hey @FichteFoll, ah yeah the plugin is by default 3.8. thanks for this. Can you elaborate this?

Are you saying it is not working for 3.8 plugins?

**Comment by FichteFoll** [comment]
I'm specifically talking about this code and propose to swap the behavior of including the Python host version:

https://github.com/kapitanluffy/sublime-plugin-logger/blob/f171b24dc6cc10b129126fbf4e72c4fab2769612/plugin_logger.py#L34-L38

**Comment by kapitanluffy** [comment]
Resolved in 2.0.2
